include: cfg/model/ddpm.yaml

model: SbmclDDPM

backbone: UNet

encoder: CnnEncoder
enc_args:
  output_shape: [512]
  output_activation: relu

sbmcl_mlp_args:
  hidden_dim: 512
  layers: 2
  output_activation: none

optim_args:
  lr: 0.001

sbmcl_kl: True
sbmcl_kl_weight: 0.00001

eval_z_samples: 5